name: bike_fit_app
description: 실내 바이크 핏 & 심박수 기반 운동 트래커
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^2.1.0
  flutter_native_splash: ^2.4.7
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  intl: ^0.19.0
  shared_preferences: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_native_splash:
  color: "#000000"
  image: assets/splash.png
  android: true
  ios: true
  fullscreen: true
  android_12:
    color: "#000000"
    image: assets/splash.png

flutter:
  uses-material-design: true

  assets:
    - assets/background.png
    - assets/splash.png
