name: over_the_bike_fit
description: A premium bike fitness app with neon UI.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/background.png
    - assets/icon/heart.png
    - assets/splash/splash_screen.png

flutter_native_splash:
  color: "#000000"
  image: assets/splash/splash_screen.png
  android_12:
    image: assets/splash/splash_screen.png
    color: "#000000"
  fullscreen: true
