name: over_the_bike_fit
version: 1.0.1+8

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^0.66.0
  permission_handler: ^5.0.3
  fl_chart: ^11.0.1

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: "^2.3.10"

flutter_launcher_icons:
  android: "ic_launcher"
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter_native_splash:
  color: "#000000"
  image: "assets/icon/app_icon.png"
  android_12:
    image: "assets/icon/app_icon.png"

flutter:
  assets:
    - assets/background.png
    - assets/icon/app_icon.png
