name: over_the_bike_fit
description: Premium bike fitness app.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/background.png
    - assets/splash/splash_screen.png
    # 아이콘 파일(app_icon.png)을 업로드하신 후 아래 주석을 해제하세요.
    # - assets/icon/app_icon.png

flutter_native_splash:
  color: "#000000"
  image: assets/splash/splash_screen.png
  android_12:
    image: assets/splash/splash_screen.png
    color: "#000000"
  fullscreen: true
  # [추가] 스플래시 이미지를 화면 전체에 꽉 채우는 옵션
  android_gravity: fill
  ios_content_mode: scaleAspectFill
