name: over_the_bike_fit
description: Premium bike fitness app.
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/background.png
    - assets/icon/heart.png
    - assets/icon/bike_ui_dark.png
    - assets/splash_screen.png # 경로를 이미지 위치에 맞게 수정함

flutter_native_splash:
  color: "#000000"
  image: assets/splash_screen.png # 경로 수정
  android_12:
    image: assets/splash_screen.png # 경로 수정
    color: "#000000"
  fullscreen: true
